services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        container_name: kai_monitoring_dashboard
        ports:
            - "8000:8080"
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        command: ["php", "artisan", "mqtt:subscribe"]
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: monitoring_dashboard
            DB_USERNAME: postgres
            DB_PASSWORD: alakadarna
            MQTT_HOST: mqtt
            MQTT_PORT: 1883
            MQTT_AUTH_USERNAME: "kaimqtt"
            MQTT_AUTH_PASSWORD: "kaimqtt"
            REVERB_HOST: reverb
            REVERB_PORT: 8080
        networks:
            - kai

    reverb:
        build:
            context: .
            dockerfile: Dockerfile.reverb
        container_name: reverb
        ports:
            - 8080:8080
        volumes:
            - reverb_data:/var/www/html
        working_dir: /var/www/html
        networks:
            - kai
        depends_on:
            - app

    db:
        image: postgis/postgis:latest
        container_name: kai_postgres
        environment:
            POSTGRES_DB: monitoring_dashboard
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: alakadarna
            MQTT_HOST: mqtt
            MQTT_PORT: 1883
        ports:
            - "5433:5432"
        volumes:
            - kai_monitordata:/var/lib/postgresql/data
        networks:
            - kai

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "8888:80"
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        networks:
            - kai

    mqtt:
        image: eclipse-mosquitto:latest
        container_name: kai_mqtt
        ports:
            - "1883:1883"
            - "9001:9001"
        networks:
            - kai
        volumes:
            - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
            - C:\\Program Files\\mosquitto\\passwd_file:/mosquitto/config/passwd_file

networks:
    kai:

volumes:
    kai_monitordata:
    mosquitto_data:
    mosquitto_log:
    reverb_data:
    pgadmin-data:
